### ISSUE TITLE
Matex improvements

### ISSUE THREAD

**Issue by mc-cat-tty** [ITIS-Enrico-Fermi/NoteSpeedup#1]
Add features:
  - [x] triangular upper and lower
  - [x] identity matrix
  - [x] diagonal
  - [x]  from list of elements (CLI)

**Comment by giuliocorradini** [comment]
A first implementation for diagonal matrices is provided with #d1ecda0a8bcafc0883cf3c7933f3774d34896af6 in the fullgeneric branch

**Comment by mc-cat-tty** [comment]
Vectors and matrix from list of elements (CLI) will instead be implemented with some interactive TUI.
